version: '3'
services:
    jenkins:
        build: .
        container_name: jenkins
        volumes:
            - jenkins_home:/home/jenkins
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "8080:8080"
            - "5000:5000"
            - "50000:50000"
volumes:
    jenkins_home: